import { Features } from "@headlessui/react/dist/utils/render";
import { ButtonLink } from "components/Button";
import { Contact } from "components/Contact";
import { Container } from "components/Container";
import { PrimaryFeatures } from "components/Features";
import { Footer } from "components/Footer";
import { Hero } from "components/Hero";
import { NavLink } from "components/NavLink";
import { Pricing } from "components/Pricing";
import { SecondaryFeatures } from "components/SecondaryFeatures";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <header className="absolute top-0 left-0 right-0 py-10">
                    <Container>
                        <nav className="relative z-50 flex justify-between">
                            <div className="flex items-center md:gap-x-12">
                                <Link href="#" aria-label="Home">
                                    <div className="flex flex-shrink-0 items-center px-6">
                                        <img
                                            className="h-7 w-auto"
                                            src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500"
                                            alt="AgentSpace"
                                        />
                                        <h4 className="ml-4 text-xl font-semibold text-gray-600">
                                            Agent
                                            <span className=" text-indigo-600">
                                                Space
                                            </span>
                                        </h4>

                                        <p className="ml-2 text-[12px] ">
                                            BETA
                                        </p>
                                    </div>
                                </Link>
                            </div>
                            <div className="flex items-center gap-x-5 md:gap-x-8">
                                <div className="hidden md:block">
                                    <ButtonLink
                                        href="https://www.agentspace.io/"
                                        variant="outlined"
                                    >
                                        Sign in
                                    </ButtonLink>
                                </div>
                                {/* <ButtonLink href="/register" variant="outlined">
                                    <span>
                                        Sign Up
                                        <span className="hidden lg:inline">
                                            today
                                        </span>
                                    </span>
                                </ButtonLink> */}
                            </div>
                        </nav>
                    </Container>
                </header>
                <Hero />
                <PrimaryFeatures />
                <SecondaryFeatures />
                <Pricing />
                <Contact />
            </main>
            <Footer />
        </>
    );
}
