version: "3.9"
services:
  db:
    container_name: app-db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    volumes:
      - db:/data/db
volumes:
  db: {}
